name: CI

on: [push]

jobs:
  factory-kit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint & Prettier
        run: |
          yarn lint:factory-kit
          yarn format
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Upload factory-kit build
        uses: actions/upload-artifact@v4
        with:
          name: factory-kit-dist
          path: dist/

  project-esm:
    needs: factory-kit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-projects/project-esm
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Install factory-kit dependencies
        working-directory: .
        run: yarn install --frozen-lockfile
      - name: Download factory-kit build
        uses: actions/download-artifact@v4
        with:
          name: factory-kit-dist
          path: ../../dist/
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        working-directory: .
        run: yarn lint:project-esm
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  project-cjs:
    needs: factory-kit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-projects/project-cjs
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Install factory-kit dependencies
        working-directory: .
        run: yarn install --frozen-lockfile
      - name: Download factory-kit build
        uses: actions/download-artifact@v4
        with:
          name: factory-kit-dist
          path: ../../dist/
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        working-directory: .
        run: yarn lint:project-cjs
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
