name: CI

on: [push]

jobs:
  factory-kit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: factory-kit - Install dependencies
        run: yarn install --frozen-lockfile

      - name: factory-kit - Lint & Prettier
        run: |
          yarn lint:factory-kit
          yarn format

      - name: factory-kit - Build
        run: yarn build

      - name: factory-kit - Test
        run: yarn test
      
      - name: project-esm - Install dependencies
        run: |
          cd test-projects/project-esm
          yarn install --frozen-lockfile
        
      - name: project-esm - Lint
        run: |
          yarn lint:project-esm

      - name: project-esm - Build
        run: |
          cd test-projects/project-esm
          yarn build

      - name: project-esm - Test
        run: | 
          cd test-projects/project-esm
          yarn test

      - name: project-cjs - Install dependencies
        run: |
          cd test-projects/project-cjs
          yarn install --frozen-lockfile

      - name: project-cjs - Lint
        run: |
          yarn lint:project-cjs

      - name: project-cjs - Build
        run: |
          cd test-projects/project-cjs
          yarn build

      - name: project-cjs - Test
        run: |
          cd test-projects/project-cjs
          yarn test
